---
title: "Enunciados"
author: "Carlos Manzano Diaz"
date: "2024-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problemas Carlos Manzano Diaz

## Problema 1
En este caso al ser un problema q no necesita enunciado dare unicamente la matriz
de decisiones y estados de la naturaleza

    a1  a2  a3  a4  
d1  1   2   0   8
d2  -2  5   4   1
d3  0   6   3   2
d4  9   4   1   5

## Problema 2

Pablo tiene 20 euros para apostar esta semana en una casa de apuestas. Como el fútbol es su deporte 
favorito lo va a invertir en un partido de fútbol. Como sabe que con 20 euros si juega a algo seguro no va a ganar mucho se plantea hacer una apuesta arriesgada, pero no sabe cual.
Su primera opción es invertir a que un jugador va a marcar 1 gol, otra es q va a provocar una amarilla,
otra que no hará ni una sola falta y otra que es la mas arriesgada que consiste en que le van a sacar a el una tarjeta amarilla.
Se pueden dar una serie de situaciones en las q según ocurra ganara mas o menos:
En el caso de q no juegue ningún momento, en el primer caso le devuelven el dinero, en el segundo le devuelven la mitad y en los otros dos lo pierde todo. En el caso de que el entrenador lo relegue al banquillo antes de que cumpla con los requisitos, en el primer caso obtiene la mitad de lo que hay invertido en ganancias, en el segundo caso le reembolsan el dinero. En caso de que cumpla el objetivo, en el primer caso obtiene de ganancias lo que invirtió, en el segundo caso obtendrá un 150% del valor invertido, en el 3 caso un 125% y en el ultimo
caso obtendrá el triple de lo invertido al ser la mas arriesgada. Por ultimo, si no ocurre eso si no que ocurre el doble, es decir, si marca dos goles, o provoca 2 amarillas, etc. En el primer caso obtiene el doble de lo invertido, en el segundo caso obtiene lo mismo q gano en el anterior estado de la naturaleza, en el tercer caso
gana el 150% de lo invertido y en el ultimo caso gana 5 veces lo invertido.

# Problemas Filomeno Aspe Moreno

## Problema 1
La matriz está definida como:
    a1  a2  a3   
d1  10  8   6 
d2  5   12  7 
d3  8   6   9 
d4  4   10  11

## Problema 2 

Un restaurante necesita decidir entre tres tipos de menú para ofrecer a sus clientes, dependiendo de la demanda esperada para las próximas temporadas.
Menús a elegir:
-Menú Tradicional.
-Menú Saludable.
-Menú Vegetariano.
Escenarios de demanda:
-Alta.
-Media.
-Baja.
Para el Menú Tradicional, en un escenario de demanda alta, se espera un beneficio de 30 mil euros, con una demanda media, el beneficio es de 20 mil euros, y en una demanda baja, de 10 mil euros.
Para el Menú Saludable, los beneficios esperados son de 40 mil euros con demanda alta, 30 mil euros con demanda media, y 15 mil euros con demanda baja.
Finalmente, para el Menú Vegetariano, se esperan 50 mil euros en demanda alta, 25 mil euros con demanda media, y 5 mil euros en un escenario de demanda baja.


# Problemas Laura Boza Molinillo

## Problema 1

Sea la tabla de decisión con 5 estados de la naturaleza y 4 alternativas de la siguiente forma:

    a1  a2  a3  a4  a5
d1  5   4   6   2   3
d2  1   7   8   7   5
d3  2   0   8   9   5
d4  4   3  -1   9  10

Resolverla tanto para situación favorable como desfavorable, con cada uno de los criterios por separado.

## Problema 2

Un chef está experimentando con diferentes ingredientes y métodos de cocción para preparar 
un nuevo plato. Tiene cuatro posibles ingredientes principales: pollo (d1), pescado (d2), 
champiñones (d3) y ternera (d4). Además, tiene cuatro métodos de cocción: asado (e1), frito (e2), 
al vapor (e3) y a la parrilla (e4). Dependiendo de la combinación de ingrediente y método de 
cocción, el tiempo total de preparación (en minutos) varía según la siguiente tabla:

    e1  e2  e3  e4
d1  45  30  25  50
d2  35  20  30  40
d3  25  15  20  35
d4  50  40  30  60

Resolverla con la función que devuelve la resolución de todos los métodos en una única tabla.
¿Qué ingrediente le recomendarías al chef?


